version: '3.0'
services:
  vk_loader:
    build: .
    image: vk_loader
    entrypoint: python3 get_photos.py
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379"
    restart: on-failure